[workspace]
resolver = "2"
members = [
    "packages/rust-client-wasm",
    "packages/rust-client",
    "packages/near-wasm",
    "packages/ipfs-integration",
    "packages/marketplace",


]

    # "contracts/near/soulbound-nft", # Requires cargo-near, exclude for now

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.dev]
overflow-checks = true





