#!/bin/bash
echo "=== SHELL INFO ==="
echo "Shell: $SHELL"
echo "Whoami: $(whoami)"
echo "PWD: $(pwd)"
echo "=== PATH ANALYSIS ==="
echo "PATH: $PATH"
echo "=== BINARY SEARCH ==="
echo "Which cargo: $(which cargo)"
echo "Which near: $(which near)"
echo "Which cargo-near: $(which cargo-near)"
echo "=== CARGO BIN DIR ==="
ls -la ~/.cargo/bin 2>/dev/null
echo "=== BASHRC DUMP ==="
cat ~/.bashrc 2>/dev/null | grep -i "export PATH"
echo "=== PROFILE DUMP ==="
cat ~/.profile 2>/dev/null | grep -i "export PATH"
echo "=== BASHR_PROFILE DUMP ==="
cat ~/.bash_profile 2>/dev/null | grep -i "export PATH"
