/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_toolparameter_free: (a: number, b: number) => void;
export const toolparameter_new: (a: number, b: number, c: number, d: number, e: number) => number;
export const toolparameter_set_range: (a: number, b: number, c: number) => void;
export const toolparameter_set_description: (a: number, b: number, c: number) => void;
export const __wbg_audioengine_free: (a: number, b: number) => void;
export const audioengine_new: () => number;
export const audioengine_process_audio_frame: (a: number, b: number, c: number) => [number, number];
export const audioengine_get_audio_levels: (a: number) => [number, number];
export const audioengine_generate_sine_wave: (a: number, b: number, c: number, d: number) => [number, number];
export const graphicsengine_new: (a: number, b: number) => number;
export const graphicsengine_generate_fractal: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const graphicsengine_generate_audio_reactive: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const graphicsengine_update_time: (a: number, b: number) => void;
export const graphicsengine_set_zoom: (a: number, b: number) => void;
export const graphicsengine_set_iterations: (a: number, b: number) => void;
export const __wbg_creativetool_free: (a: number, b: number) => void;
export const creativetool_new: (a: number, b: number, c: number, d: number) => number;
export const creativetool_add_parameter: (a: number, b: number) => void;
export const creativetool_set_code: (a: number, b: number, c: number) => void;
export const creativetool_get_name: (a: number) => [number, number];
export const creativetool_get_type: (a: number) => [number, number];
export const creativetool_to_json: (a: number) => any;
export const __wbg_creativeengine_free: (a: number, b: number) => void;
export const creativeengine_new: (a: number, b: number) => number;
export const creativeengine_process_audio: (a: number, b: number, c: number) => [number, number];
export const creativeengine_generate_visuals: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const creativeengine_update: (a: number, b: number) => void;
export const creativeengine_get_tool_names: (a: number) => any;
export const creativeengine_get_tool_info: (a: number, b: number) => any;
export const creativeengine_set_graphics_params: (a: number, b: number, c: number, d: number, e: number) => void;
export const main: () => void;
export const __wbg_graphicsengine_free: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
