/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_fractalparameters_free: (a: number, b: number) => void;
export const fractalparameters_new: () => number;
export const fractalparameters_set_iterations: (a: number, b: number) => void;
export const fractalparameters_set_zoom: (a: number, b: number) => void;
export const fractalparameters_set_center: (a: number, b: number, c: number) => void;
export const fractalparameters_iterations: (a: number) => number;
export const fractalparameters_zoom: (a: number) => number;
export const fractalparameters_center_x: (a: number) => number;
export const fractalparameters_center_y: (a: number) => number;
export const __wbg_audiometrics_free: (a: number, b: number) => void;
export const audiometrics_new: () => number;
export const audiometrics_bpm: (a: number) => number;
export const audiometrics_beats_detected: (a: number) => number;
export const audiometrics_peak_left: (a: number) => number;
export const audiometrics_peak_right: (a: number) => number;
export const audiometrics_rms_left: (a: number) => number;
export const audiometrics_rms_right: (a: number) => number;
export const __wbg_creativeengine_free: (a: number, b: number) => void;
export const creativeengine_new: () => number;
export const creativeengine_process_audio: (a: number, b: number, c: number) => [number, number, number];
export const creativeengine_generate_fractal: (a: number, b: number, c: number) => [number, number];
export const creativeengine_fractal_params: (a: number) => number;
export const creativeengine_pan_fractal: (a: number, b: number, c: number) => void;
export const creativeengine_zoom_fractal: (a: number, b: number, c: number, d: number) => void;
export const __wbg_audioprocessor_free: (a: number, b: number) => void;
export const audioprocessor_new: (a: number, b: number) => number;
export const audioprocessor_generate_sine: (a: number, b: number, c: number) => [number, number];
export const audioprocessor_generate_square: (a: number, b: number, c: number) => [number, number];
export const audioprocessor_analyze_frequencies: (a: number, b: number, c: number) => [number, number];
export const main: () => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
