/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CrossChainDataBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_METADATA_SIZE"
      | "activeStreamIds"
      | "aiDataPackets"
      | "authorizeBridge"
      | "authorizedBridges"
      | "chainIdMapping"
      | "createDataStream"
      | "dataStreams"
      | "deactivateStream"
      | "emotionalMetadata"
      | "getAIDataPacket"
      | "getActiveStreamsCount"
      | "getStreamData"
      | "getStreamIds"
      | "owner"
      | "processAIData"
      | "renounceOwnership"
      | "revokeBridge"
      | "storeEmotionalMetadata"
      | "streamCounter"
      | "transferCrossChainData"
      | "transferOwnership"
      | "updateChainMapping"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AIDataProcessed"
      | "CrossChainDataTransferred"
      | "EmotionalDataStored"
      | "OwnershipTransferred"
      | "StreamCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_METADATA_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeStreamIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "aiDataPackets",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedBridges",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "chainIdMapping",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "createDataStream",
    values: [string, string, string, string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dataStreams", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deactivateStream",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "emotionalMetadata",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAIDataPacket",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveStreamsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStreamData",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getStreamIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processAIData",
    values: [string, string, string, BytesLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeEmotionalMetadata",
    values: [string, string, BigNumberish, string, BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "streamCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferCrossChainData",
    values: [string, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateChainMapping",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_METADATA_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeStreamIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aiDataPackets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedBridges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "chainIdMapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDataStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emotionalMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAIDataPacket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveStreamsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStreamData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStreamIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processAIData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeEmotionalMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferCrossChainData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateChainMapping",
    data: BytesLike
  ): Result;
}

export namespace AIDataProcessedEvent {
  export type InputTuple = [
    packetId: string,
    streamId: string,
    dataType: string,
    confidence: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    packetId: string,
    streamId: string,
    dataType: string,
    confidence: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    packetId: string;
    streamId: string;
    dataType: string;
    confidence: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainDataTransferredEvent {
  export type InputTuple = [
    streamId: string,
    fromChain: string,
    toChain: string,
    data: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    fromChain: string,
    toChain: string,
    data: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    streamId: string;
    fromChain: string;
    toChain: string;
    data: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmotionalDataStoredEvent {
  export type InputTuple = [
    streamId: string,
    emotionType: string,
    intensity: BigNumberish,
    vectorHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    emotionType: string,
    intensity: bigint,
    vectorHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    streamId: string;
    emotionType: string;
    intensity: bigint;
    vectorHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    streamId: string,
    creator: AddressLike,
    sourceChain: string,
    targetChain: string,
    ipfsHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    streamId: string,
    creator: string,
    sourceChain: string,
    targetChain: string,
    ipfsHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    streamId: string;
    creator: string;
    sourceChain: string;
    targetChain: string;
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainDataBridge extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainDataBridge;
  waitForDeployment(): Promise<this>;

  interface: CrossChainDataBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_METADATA_SIZE: TypedContractMethod<[], [bigint], "view">;

  activeStreamIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  aiDataPackets: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, string, bigint] & {
        packetId: string;
        streamId: string;
        dataType: string;
        aiData: string;
        signature: string;
        confidence: bigint;
        modelVersion: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  authorizeBridge: TypedContractMethod<
    [_bridge: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedBridges: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  chainIdMapping: TypedContractMethod<[arg0: string], [string], "view">;

  createDataStream: TypedContractMethod<
    [
      _streamId: string,
      _sourceChain: string,
      _targetChain: string,
      _ipfsHash: string,
      _encryptedData: BytesLike,
      _epoch: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  dataStreams: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        streamId: string;
        creator: string;
        sourceChain: string;
        targetChain: string;
        ipfsHash: string;
        encryptedData: string;
        timestamp: bigint;
        epoch: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  deactivateStream: TypedContractMethod<
    [_streamId: string],
    [void],
    "nonpayable"
  >;

  emotionalMetadata: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, string, string, bigint] & {
        emotionType: string;
        intensity: bigint;
        vectorHash: string;
        merkleRoot: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getAIDataPacket: TypedContractMethod<
    [_packetId: string],
    [
      [string, string, string, bigint, string, bigint] & {
        streamId: string;
        dataType: string;
        aiData: string;
        confidence: bigint;
        modelVersion: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getActiveStreamsCount: TypedContractMethod<[], [bigint], "view">;

  getStreamData: TypedContractMethod<
    [_streamId: string],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        creator: string;
        sourceChain: string;
        targetChain: string;
        ipfsHash: string;
        timestamp: bigint;
        epoch: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getStreamIds: TypedContractMethod<
    [_page: BigNumberish, _perPage: BigNumberish],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processAIData: TypedContractMethod<
    [
      _packetId: string,
      _streamId: string,
      _dataType: string,
      _aiData: BytesLike,
      _signature: BytesLike,
      _confidence: BigNumberish,
      _modelVersion: string
    ],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeBridge: TypedContractMethod<
    [_bridge: AddressLike],
    [void],
    "nonpayable"
  >;

  storeEmotionalMetadata: TypedContractMethod<
    [
      _streamId: string,
      _emotionType: string,
      _intensity: BigNumberish,
      _vectorHash: string,
      _merkleRoot: BytesLike,
      _tags: string[]
    ],
    [string],
    "nonpayable"
  >;

  streamCounter: TypedContractMethod<[], [bigint], "view">;

  transferCrossChainData: TypedContractMethod<
    [
      _streamId: string,
      _targetChain: string,
      _data: BytesLike,
      _signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateChainMapping: TypedContractMethod<
    [_chainName: string, _chainId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_METADATA_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeStreamIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "aiDataPackets"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, bigint, string, bigint] & {
        packetId: string;
        streamId: string;
        dataType: string;
        aiData: string;
        signature: string;
        confidence: bigint;
        modelVersion: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeBridge"
  ): TypedContractMethod<[_bridge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedBridges"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "chainIdMapping"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "createDataStream"
  ): TypedContractMethod<
    [
      _streamId: string,
      _sourceChain: string,
      _targetChain: string,
      _ipfsHash: string,
      _encryptedData: BytesLike,
      _epoch: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dataStreams"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        streamId: string;
        creator: string;
        sourceChain: string;
        targetChain: string;
        ipfsHash: string;
        encryptedData: string;
        timestamp: bigint;
        epoch: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateStream"
  ): TypedContractMethod<[_streamId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emotionalMetadata"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, string, string, bigint] & {
        emotionType: string;
        intensity: bigint;
        vectorHash: string;
        merkleRoot: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAIDataPacket"
  ): TypedContractMethod<
    [_packetId: string],
    [
      [string, string, string, bigint, string, bigint] & {
        streamId: string;
        dataType: string;
        aiData: string;
        confidence: bigint;
        modelVersion: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveStreamsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStreamData"
  ): TypedContractMethod<
    [_streamId: string],
    [
      [string, string, string, string, bigint, bigint, boolean] & {
        creator: string;
        sourceChain: string;
        targetChain: string;
        ipfsHash: string;
        timestamp: bigint;
        epoch: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStreamIds"
  ): TypedContractMethod<
    [_page: BigNumberish, _perPage: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processAIData"
  ): TypedContractMethod<
    [
      _packetId: string,
      _streamId: string,
      _dataType: string,
      _aiData: BytesLike,
      _signature: BytesLike,
      _confidence: BigNumberish,
      _modelVersion: string
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeBridge"
  ): TypedContractMethod<[_bridge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storeEmotionalMetadata"
  ): TypedContractMethod<
    [
      _streamId: string,
      _emotionType: string,
      _intensity: BigNumberish,
      _vectorHash: string,
      _merkleRoot: BytesLike,
      _tags: string[]
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "streamCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferCrossChainData"
  ): TypedContractMethod<
    [
      _streamId: string,
      _targetChain: string,
      _data: BytesLike,
      _signature: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateChainMapping"
  ): TypedContractMethod<
    [_chainName: string, _chainId: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AIDataProcessed"
  ): TypedContractEvent<
    AIDataProcessedEvent.InputTuple,
    AIDataProcessedEvent.OutputTuple,
    AIDataProcessedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainDataTransferred"
  ): TypedContractEvent<
    CrossChainDataTransferredEvent.InputTuple,
    CrossChainDataTransferredEvent.OutputTuple,
    CrossChainDataTransferredEvent.OutputObject
  >;
  getEvent(
    key: "EmotionalDataStored"
  ): TypedContractEvent<
    EmotionalDataStoredEvent.InputTuple,
    EmotionalDataStoredEvent.OutputTuple,
    EmotionalDataStoredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;

  filters: {
    "AIDataProcessed(string,string,string,uint256,uint256)": TypedContractEvent<
      AIDataProcessedEvent.InputTuple,
      AIDataProcessedEvent.OutputTuple,
      AIDataProcessedEvent.OutputObject
    >;
    AIDataProcessed: TypedContractEvent<
      AIDataProcessedEvent.InputTuple,
      AIDataProcessedEvent.OutputTuple,
      AIDataProcessedEvent.OutputObject
    >;

    "CrossChainDataTransferred(string,string,string,bytes,uint256)": TypedContractEvent<
      CrossChainDataTransferredEvent.InputTuple,
      CrossChainDataTransferredEvent.OutputTuple,
      CrossChainDataTransferredEvent.OutputObject
    >;
    CrossChainDataTransferred: TypedContractEvent<
      CrossChainDataTransferredEvent.InputTuple,
      CrossChainDataTransferredEvent.OutputTuple,
      CrossChainDataTransferredEvent.OutputObject
    >;

    "EmotionalDataStored(string,string,uint256,string,uint256)": TypedContractEvent<
      EmotionalDataStoredEvent.InputTuple,
      EmotionalDataStoredEvent.OutputTuple,
      EmotionalDataStoredEvent.OutputObject
    >;
    EmotionalDataStored: TypedContractEvent<
      EmotionalDataStoredEvent.InputTuple,
      EmotionalDataStoredEvent.OutputTuple,
      EmotionalDataStoredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StreamCreated(string,address,string,string,string,uint256)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
  };
}
